### ISSUE TITLE
Chat filtering client-side option

### ISSUE THREAD

**Issue by intOrfloat** [Squarific/Anondraw#113]
A little menu that lets you mute people(just sound mute or lower their message opacity 0% - 100%) based on their uKey(provided by playerlist)
Also advanced options to have chat sounds play only when matching user provided regex(defaults provided) like 'help' or 'ink' or 'grief/greif'

**Comment by lukasdietrich** [comment]
The chat does not currently send a `uKey` and names are not unique

**Comment by Squarific** [comment]
I'm not against adding uKey to the emitted data

**Comment by Squarific** [comment]
This can be closed right?
