### ISSUE TITLE
Keep people in the list after they leave

### ISSUE THREAD

**Issue by Squarific** [Squarific/Anondraw#42]
Make it possible to somehow kickban people who recently left.

**Comment by lukasdietrich** [comment]
Maybe moderator/admin dashboard with `x` most recent users ?

**Comment by Squarific** [comment]
Yea probably gonna do something like that.

**Comment by Squarific** [comment]
Better would be to create a tool to see who drew a line and make the possibility to undo using that.

**Comment by Squarific** [comment]
Decided to just show the people who left in chat because that was the easiest method. https://github.com/Squarific/Anondraw/commit/a88a2948370bef32cf8d8598f39d2fd56295e26f
