### ISSUE TITLE
Who drew this tool

### ISSUE THREAD

**Issue by Squarific** [Squarific/Anondraw#49]

**Comment by Squarific** [comment]
Maybe this issue should be placed under paint.js

**Comment by intOrfloat** [comment]
I'm thinking we add the option here after drawing a selection. it'll say 'Who drew in this area'. And then spit out the list of line owners with the ban option next to their names. (good for people who disconnected and you're not sure who did it)
![image](https://cloud.githubusercontent.com/assets/20852626/19853521/0d554784-9f40-11e6-86fa-af518d0689d2.png)

![](https://cdn.discordapp.com/attachments/221656328018460672/242617788198420481/unknown.png)

**Comment by Squarific** [comment]
Oh using the region tool is smart
